version: "3"

services:
    php:
        build:
            context: ./ # Indica onde está o arquivo Dockerfile
            dockerfile: Dockerfile
        container_name: basedockerphp # Apelido para o container
        links:
          - db
        volumes:
            # troque o /home/filipe/www/basedockerphp pelo caminho do seu projeto, deixe :/var/www/html/ como está 
            - /home/filipe/www/basedockerphp:/var/www/html/ # Irá copiar o conteúdo da pasta src para o container
        ports: # Mapear as portas para ficarem visiveis na máquina host
            - "80:80"

    db:
        image: mysql:latest
        container_name: mysql_name # Apelido para o container
        ports:
        - "3306:3306"
        volumes:
        - data:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=root
    # app:
    #     image: phpmyadmin/phpmyadmin:latest
    #     container_name: phpmyadmin # Apelido para o container
    #     links:
    #     - db
    #     ports:
    #     - 8080:80
    #     environment:
    #     - PMA_ARBITRARY=1    
volumes:
  data: